"""
Default Indian recipes to suggest when API doesn't return good results
"""

INDIAN_RECIPES = [
    {
        'id': 'indian_1',
        'title': 'Vegetable Pulao',
        'category': 'Main Course',
        'image': 'https://via.placeholder.com/400x300/FF9933/FFFFFF?text=Vegetable+Pulao',
        'instructions': '1. Wash and soak rice for 30 minutes. 2. Heat oil/ghee in a pressure cooker. 3. Add whole spices (cumin, bay leaf, cloves). 4. Add chopped vegetables and sauté. 5. Add rice, water, and salt. 6. Pressure cook for 2 whistles.',
        'short_instructions': 'Aromatic rice dish with mixed vegetables and Indian spices.',
        'ingredients': [
            {'name': 'Basmati Rice', 'amount': 1, 'unit': 'cup'},
            {'name': 'Mixed Vegetables', 'amount': 2, 'unit': 'cups'},
            {'name': 'Onion', 'amount': 1, 'unit': 'large'},
            {'name': 'Ginger Garlic Paste', 'amount': 1, 'unit': 'tsp'},
            {'name': 'Garam Masala', 'amount': 1, 'unit': 'tsp'},
            {'name': 'Cumin Seeds', 'amount': 1, 'unit': 'tsp'},
            {'name': 'Oil/Ghee', 'amount': 2, 'unit': 'tbsp'},
            {'name': 'Salt', 'amount': 1, 'unit': 'tsp'},
        ],
        'cooking_time': 30,
        'servings': 4,
        'tags': ['Indian', 'Vegetarian', 'Rice', 'Main Course'],
        'is_indian': True,
    },
    {
        'id': 'indian_2',
        'title': 'Chana Masala',
        'category': 'Main Course',
        'image': 'https://via.placeholder.com/400x300/FF9933/FFFFFF?text=Chana+Masala',
        'instructions': '1. Soak chickpeas overnight. 2. Pressure cook until soft. 3. Heat oil in a pan. 4. Add cumin, onions, ginger-garlic paste. 5. Add tomatoes and spices. 6. Add cooked chickpeas and simmer.',
        'short_instructions': 'Spicy chickpea curry with Indian spices.',
        'ingredients': [
            {'name': 'Chickpeas', 'amount': 1, 'unit': 'cup'},
            {'name': 'Onion', 'amount': 2, 'unit': 'medium'},
            {'name': 'Tomatoes', 'amount': 3, 'unit': 'medium'},
            {'name': 'Ginger Garlic Paste', 'amount': 1, 'unit': 'tbsp'},
            {'name': 'Chana Masala Powder', 'amount': 2, 'unit': 'tbsp'},
            {'name': 'Turmeric Powder', 'amount': 0.5, 'unit': 'tsp'},
            {'name': 'Coriander Powder', 'amount': 1, 'unit': 'tsp'},
            {'name': 'Oil', 'amount': 3, 'unit': 'tbsp'},
        ],
        'cooking_time': 45,
        'servings': 4,
        'tags': ['Indian', 'Vegetarian', 'Curry', 'Chickpeas'],
        'is_indian': True,
    },
    {
        'id': 'indian_3',
        'title': 'Palak Paneer',
        'category': 'Main Course',
        'image': 'https://via.placeholder.com/400x300/FF9933/FFFFFF?text=Palak+Paneer',
        'instructions': '1. Blanch spinach and make puree. 2. Heat oil/ghee. 3. Add cumin, onions, ginger-garlic. 4. Add spinach puree and spices. 5. Add paneer cubes and cream. 6. Simmer for 5 minutes.',
        'short_instructions': 'Cottage cheese in spinach gravy.',
        'ingredients': [
            {'name': 'Paneer', 'amount': 200, 'unit': 'grams'},
            {'name': 'Spinach', 'amount': 2, 'unit': 'bunches'},
            {'name': 'Onion', 'amount': 1, 'unit': 'large'},
            {'name': 'Tomatoes', 'amount': 2, 'unit': 'medium'},
            {'name': 'Ginger Garlic Paste', 'amount': 1, 'unit': 'tbsp'},
            {'name': 'Garam Masala', 'amount': 1, 'unit': 'tsp'},
            {'name': 'Cumin Powder', 'amount': 1, 'unit': 'tsp'},
            {'name': 'Cream', 'amount': 2, 'unit': 'tbsp'},
        ],
        'cooking_time': 35,
        'servings': 4,
        'tags': ['Indian', 'Vegetarian', 'Paneer', 'Spinach'],
        'is_indian': True,
    },
    {
        'id': 'indian_4',
        'title': 'Dal Tadka',
        'category': 'Main Course',
        'image': 'https://via.placeholder.com/400x300/FF9933/FFFFFF?text=Dal+Tadka',
        'instructions': '1. Cook lentils until soft. 2. Prepare tadka with ghee, cumin, garlic, red chilies. 3. Add tadka to cooked dal. 4. Garnish with coriander.',
        'short_instructions': 'Tempered lentil soup.',
        'ingredients': [
            {'name': 'Yellow Lentils', 'amount': 1, 'unit': 'cup'},
            {'name': 'Onion', 'amount': 1, 'unit': 'medium'},
            {'name': 'Tomatoes', 'amount': 2, 'unit': 'medium'},
            {'name': 'Ginger Garlic Paste', 'amount': 1, 'unit': 'tsp'},
            {'name': 'Turmeric Powder', 'amount': 0.5, 'unit': 'tsp'},
            {'name': 'Cumin Seeds', 'amount': 1, 'unit': 'tsp'},
            {'name': 'Ghee', 'amount': 2, 'unit': 'tbsp'},
            {'name': 'Coriander Leaves', 'amount': 0.25, 'unit': 'cup'},
        ],
        'cooking_time': 40,
        'servings': 4,
        'tags': ['Indian', 'Vegetarian', 'Lentils', 'Soup'],
        'is_indian': True,
    },
    {
        'id': 'indian_5',
        'title': 'Aloo Gobi',
        'category': 'Main Course',
        'image': 'https://via.placeholder.com/400x300/FF9933/FFFFFF?text=Aloo+Gobi',
        'instructions': '1. Heat oil in a pan. 2. Add cumin seeds, onions, ginger-garlic. 3. Add potatoes and cauliflower. 4. Add spices and cook covered. 5. Garnish with coriander.',
        'short_instructions': 'Potato and cauliflower dry curry.',
        'ingredients': [
            {'name': 'Potatoes', 'amount': 3, 'unit': 'medium'},
            {'name': 'Cauliflower', 'amount': 1, 'unit': 'small'},
            {'name': 'Onion', 'amount': 1, 'unit': 'large'},
            {'name': 'Tomatoes', 'amount': 2, 'unit': 'medium'},
            {'name': 'Ginger Garlic Paste', 'amount': 1, 'unit': 'tsp'},
            {'name': 'Turmeric Powder', 'amount': 0.5, 'unit': 'tsp'},
            {'name': 'Coriander Powder', 'amount': 1, 'unit': 'tsp'},
            {'name': 'Oil', 'amount': 3, 'unit': 'tbsp'},
        ],
        'cooking_time': 30,
        'servings': 4,
        'tags': ['Indian', 'Vegetarian', 'Potato', 'Cauliflower'],
        'is_indian': True,
    },
    {
        'id': 'indian_6',
        'title': 'Butter Chicken',
        'category': 'Main Course',
        'image': 'https://via.placeholder.com/400x300/FF9933/FFFFFF?text=Butter+Chicken',
        'instructions': '1. Marinate chicken in yogurt and spices. 2. Grill or pan-fry chicken. 3. Make gravy with tomatoes, cream, and butter. 4. Add chicken to gravy and simmer.',
        'short_instructions': 'Creamy tomato-based chicken curry.',
        'ingredients': [
            {'name': 'Chicken', 'amount': 500, 'unit': 'grams'},
            {'name': 'Tomatoes', 'amount': 4, 'unit': 'large'},
            {'name': 'Onion', 'amount': 2, 'unit': 'medium'},
            {'name': 'Ginger Garlic Paste', 'amount': 1, 'unit': 'tbsp'},
            {'name': 'Butter', 'amount': 3, 'unit': 'tbsp'},
            {'name': 'Cream', 'amount': 0.5, 'unit': 'cup'},
            {'name': 'Garam Masala', 'amount': 1, 'unit': 'tsp'},
            {'name': 'Kasuri Methi', 'amount': 1, 'unit': 'tsp'},
        ],
        'cooking_time': 50,
        'servings': 4,
        'tags': ['Indian', 'Non-Vegetarian', 'Chicken', 'Creamy'],
        'is_indian': True,
    },
    {
        'id': 'indian_7',
        'title': 'Rajma Masala',
        'category': 'Main Course',
        'image': 'https://via.placeholder.com/400x300/FF9933/FFFFFF?text=Rajma+Masala',
        'instructions': '1. Soak kidney beans overnight. 2. Pressure cook until soft. 3. Make masala with onions, tomatoes, spices. 4. Add beans and simmer.',
        'short_instructions': 'Kidney bean curry.',
        'ingredients': [
            {'name': 'Kidney Beans', 'amount': 1, 'unit': 'cup'},
            {'name': 'Onion', 'amount': 2, 'unit': 'large'},
            {'name': 'Tomatoes', 'amount': 3, 'unit': 'medium'},
            {'name': 'Ginger Garlic Paste', 'amount': 1, 'unit': 'tbsp'},
            {'name': 'Rajma Masala', 'amount': 2, 'unit': 'tbsp'},
            {'name': 'Coriander Powder', 'amount': 1, 'unit': 'tsp'},
            {'name': 'Oil', 'amount': 3, 'unit': 'tbsp'},
            {'name': 'Coriander Leaves', 'amount': 0.25, 'unit': 'cup'},
        ],
        'cooking_time': 60,
        'servings': 4,
        'tags': ['Indian', 'Vegetarian', 'Kidney Beans', 'Curry'],
        'is_indian': True,
    },
    {
        'id': 'indian_8',
        'title': 'Vegetable Biryani',
        'category': 'Main Course',
        'image': 'https://via.placeholder.com/400x300/FF9933/FFFFFF?text=Vegetable+Biryani',
        'instructions': '1. Soak rice. 2. Prepare vegetable masala. 3. Layer rice and masala in pot. 4. Cook on dum (steam). 5. Garnish with fried onions and mint.',
        'short_instructions': 'Fragrant rice with vegetables and spices.',
        'ingredients': [
            {'name': 'Basmati Rice', 'amount': 2, 'unit': 'cups'},
            {'name': 'Mixed Vegetables', 'amount': 3, 'unit': 'cups'},
            {'name': 'Onion', 'amount': 2, 'unit': 'large'},
            {'name': 'Yogurt', 'amount': 0.5, 'unit': 'cup'},
            {'name': 'Biryani Masala', 'amount': 2, 'unit': 'tbsp'},
            {'name': 'Saffron', 'amount': 0.25, 'unit': 'tsp'},
            {'name': 'Ghee', 'amount': 4, 'unit': 'tbsp'},
            {'name': 'Mint Leaves', 'amount': 0.5, 'unit': 'cup'},
        ],
        'cooking_time': 60,
        'servings': 6,
        'tags': ['Indian', 'Vegetarian', 'Biryani', 'Rice'],
        'is_indian': True,
    },
    {
        'id': 'indian_9',
        'title': 'Pav Bhaji',
        'category': 'Snack',
        'image': 'https://via.placeholder.com/400x300/FF9933/FFFFFF?text=Pav+Bhaji',
        'instructions': '1. Boil and mash vegetables. 2. Cook with pav bhaji masala and butter. 3. Toast buns with butter. 4. Serve with chopped onions and lemon.',
        'short_instructions': 'Spicy vegetable mash with buttered buns.',
        'ingredients': [
            {'name': 'Mixed Vegetables', 'amount': 4, 'unit': 'cups'},
            {'name': 'Potatoes', 'amount': 2, 'unit': 'large'},
            {'name': 'Tomatoes', 'amount': 3, 'unit': 'medium'},
            {'name': 'Onion', 'amount': 2, 'unit': 'large'},
            {'name': 'Pav Bhaji Masala', 'amount': 3, 'unit': 'tbsp'},
            {'name': 'Butter', 'amount': 4, 'unit': 'tbsp'},
            {'name': 'Buns', 'amount': 8, 'unit': 'pieces'},
            {'name': 'Lemon', 'amount': 2, 'unit': 'pieces'},
        ],
        'cooking_time': 40,
        'servings': 4,
        'tags': ['Indian', 'Vegetarian', 'Street Food', 'Snack'],
        'is_indian': True,
    },
    {
        'id': 'indian_10',
        'title': 'Masala Dosa',
        'category': 'Breakfast',
        'image': 'https://via.placeholder.com/400x300/FF9933/FFFFFF?text=Masala+Dosa',
        'instructions': '1. Prepare dosa batter (rice and lentils). 2. Make potato masala filling. 3. Spread batter on hot griddle. 4. Add filling and fold.',
        'short_instructions': 'Crispy crepe with potato filling.',
        'ingredients': [
            {'name': 'Dosa Batter', 'amount': 4, 'unit': 'cups'},
            {'name': 'Potatoes', 'amount': 4, 'unit': 'large'},
            {'name': 'Onion', 'amount': 2, 'unit': 'large'},
            {'name': 'Mustard Seeds', 'amount': 1, 'unit': 'tsp'},
            {'name': 'Curry Leaves', 'amount': 10, 'unit': 'leaves'},
            {'name': 'Oil', 'amount': 4, 'unit': 'tbsp'},
            {'name': 'Chana Dal', 'amount': 1, 'unit': 'tsp'},
            {'name': 'Coconut Chutney', 'amount': 1, 'unit': 'cup'},
        ],
        'cooking_time': 45,
        'servings': 4,
        'tags': ['Indian', 'Vegetarian', 'Breakfast', 'South Indian'],
        'is_indian': True,
    },
    {
        'id': 'indian_11',
        'title': 'Samosa',
        'category': 'Snack',
        'image': 'https://via.placeholder.com/400x300/FF9933/FFFFFF?text=Samosa',
        'instructions': '1. Make dough with flour and oil. 2. Prepare potato-pea filling. 3. Shape samosas. 4. Deep fry until golden.',
        'short_instructions': 'Crispy pastry with potato filling.',
        'ingredients': [
            {'name': 'All Purpose Flour', 'amount': 2, 'unit': 'cups'},
            {'name': 'Potatoes', 'amount': 3, 'unit': 'large'},
            {'name': 'Peas', 'amount': 0.5, 'unit': 'cup'},
            {'name': 'Cumin Seeds', 'amount': 1, 'unit': 'tsp'},
            {'name': 'Coriander Powder', 'amount': 1, 'unit': 'tsp'},
            {'name': 'Garam Masala', 'amount': 0.5, 'unit': 'tsp'},
            {'name': 'Oil', 'amount': 2, 'unit': 'cups'},
            {'name': 'Green Chilies', 'amount': 2, 'unit': 'pieces'},
        ],
        'cooking_time': 60,
        'servings': 6,
        'tags': ['Indian', 'Vegetarian', 'Snack', 'Street Food'],
        'is_indian': True,
    },
    {
        'id': 'indian_12',
        'title': 'Roti/Chapati',
        'category': 'Bread',
        'image': 'https://via.placeholder.com/400x300/FF9933/FFFFFF?text=Roti+Chapati',
        'instructions': '1. Knead dough with wheat flour and water. 2. Rest for 30 minutes. 3. Roll into circles. 4. Cook on hot tawa.',
        'short_instructions': 'Whole wheat flatbread.',
        'ingredients': [
            {'name': 'Wheat Flour', 'amount': 2, 'unit': 'cups'},
            {'name': 'Water', 'amount': 1, 'unit': 'cup'},
            {'name': 'Salt', 'amount': 0.5, 'unit': 'tsp'},
            {'name': 'Oil', 'amount': 1, 'unit': 'tbsp'},
        ],
        'cooking_time': 30,
        'servings': 4,
        'tags': ['Indian', 'Vegetarian', 'Bread', 'Basic'],
        'is_indian': True,
    }
]