# Generated by Django 6.0.1 on 2026-01-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='unit',
            field=models.CharField(max_length=50),
        ),
    ]
